name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.100-preview.7.23376.3'  # Replace with your .NET version

      # Build .NET project
      - name: Build .NET project
        run: dotnet build

      # Future placeholder for test steps
      # - name: Run tests
      #   run: <test command here>
